server:
  port: 8081
 
spring:
  application:
    name: product-service
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

